# Header
menu:
  Home: /
  Archives: /archives
#rss: /atom.xml
#github: https://github.com/howiefh

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- about_me
- calendar
- category
- tag
  #- tagcloud
- archive
- recent_posts
  #- duoshuo_recent_comments
- links

# Miscellaneous
#google_analytics:
favicon: /favicon.ico
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:

# Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
# Scroll to top
go_top: true

# duoshuo
duoshuo_shortname: stanleychan1986

# baidu share
#baidushare: true

# blogroll
links:
- name: 闷道 
  link: http://maintao.com

# about me
about_me:
  title: 关于我
  avatar: /images/icon.jpg
  texts:
    - 码农
    - 在北京
    - 金陵人士

# display updated
display_updated: true
